### ISSUE TITLE
Is there anyway to use "Visualizer" in ubuntu or win11？ Thanks!

### ISSUE THREAD

**Issue by HONGcalmJIN** [Kei18/pibt2#10]

**Comment by Kei18** [comment]
Hi, at least for Ubuntu, the following visualizer is available.
https://github.com/Kei18/mapf-visualizer

Not sure about Windows.

**Comment by HONGcalmJIN** [comment]
Yes, that's great! It works in ubuntu.
Maybe you can add this method in readme to help more people.
Since not everyone has macos, but usually has ubuntu.
Thanks again！

**Comment by Kei18** [comment]
Sure, thanks for the suggestion.

Cheers, Kei
